import { useEffect, useState } from 'react';
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  PieChart,
  Pie,
  Cell,
  LineChart,
  Line,
} from 'recharts';
import {
  Trash2,
  Recycle,
  Percent,
  Truck,
  AlertTriangle,
  MapPinned,
  Sparkles,
  ShieldCheck,
} from 'lucide-react';
import AppLayout from '../components/AppLayout';
import { PageHead, Pill, statusTone, priorityTone } from '../components/Bits';
import StatCard from '../components/StatCard';
import { api, resolveImageUrl } from '../services/api';
import { useAuth } from '../context/AuthContext';

const CHART_COLORS = ['#4fb8e6', '#49e6a6', '#f0a83e', '#a68cf0', '#8fa79c', '#ff6f61', '#ff4d4d', '#5d7a6f'];
const chartTextStyle = { fontSize: 11, fill: 'var(--ink-muted)' };

function ChartCard({ title, children, subtitle }) {
  return (
    <div className="card">
      <div className="section-label" style={{ marginBottom: subtitle ? 2 : 14 }}>{title}</div>
      {subtitle && <div style={{ fontSize: 11.5, color: 'var(--ink-faint)', marginBottom: 14 }}>{subtitle}</div>}
      <div style={{ width: '100%', height: 240 }}>{children}</div>
    </div>
  );
}

export default function Dashboard() {
  const { isAdmin } = useAuth();
  const [stats, setStats] = useState(null);
  const [charts, setCharts] = useState(null);
  const [insights, setInsights] = useState([]);
  const [allReports, setAllReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;
    async function load() {
      setLoading(true);
      setError('');
      try {
        const calls = [api.getDashboardStats(), api.getDashboardCharts(), api.getDashboardInsights()];
        if (isAdmin) calls.push(api.getAllReports());
        const results = await Promise.all(calls);
        if (cancelled) return;
        setStats(results[0].data);
        setCharts(results[1].data);
        setInsights(results[2].data || []);
        if (isAdmin) setAllReports(results[3].data || []);
      } catch (err) {
        if (!cancelled) setError(err.message || 'Failed to load dashboard data');
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => { cancelled = true; };
  }, [isAdmin]);

  if (loading) {
    return (
      <AppLayout title="Smart Dashboard" subtitle="City-wide waste operations, live">
        <div className="empty-state" style={{ marginTop: 60 }}>
          <span className="spinner-ring" style={{ margin: '0 auto 10px' }} />
          <strong>Loading live data…</strong>
        </div>
      </AppLayout>
    );
  }

  if (error) {
    return (
      <AppLayout title="Smart Dashboard" subtitle="City-wide waste operations, live">
        <div className="card">
          <div className="empty-state">
            <AlertTriangle />
            <strong>Couldn't load the dashboard</strong>
            <span>{error}</span>
          </div>
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout title="Smart Dashboard" subtitle={isAdmin ? 'Every zone, every report — admin view' : 'City-wide analytics'}>
      <PageHead
        title="Smart Dashboard"
        subtitle={
          isAdmin
            ? 'A live, admin-only view of every report across every zone, plus city-wide analytics.'
            : 'City-wide analytics computed live from every citizen report. Your own contributions live under "My Impact".'
        }
      />

      <div className="grid grid-4" style={{ marginBottom: 20 }}>
        <StatCard icon={Trash2} tone="mint" label="Total Waste Collected" value={`${stats.totalWasteCollectedKg} kg`} />
        <StatCard icon={Recycle} tone="azure" label="Total Waste Recycled" value={`${stats.totalWasteRecycledKg} kg`} />
        <StatCard icon={Percent} tone="violet" label="Recycling Rate" value={`${stats.recyclingRate}%`} />
        <StatCard icon={Truck} tone="amber" label="Active Pickup Requests" value={stats.activePickupRequests} />
        <StatCard icon={AlertTriangle} tone="coral" label="High-Risk Bins" value={stats.highRiskBins} />
        <StatCard icon={MapPinned} tone="coral" label="Active Illegal Dumping Reports" value={stats.activeIllegalDumpingReports} />
      </div>

      <div className="grid grid-2" style={{ marginBottom: 20 }}>
        <ChartCard title="Waste generated by category" subtitle="Number of reports this period">
          {charts.wasteByCategory.length === 0 ? (
            <div className="empty-state"><span>No reports yet.</span></div>
          ) : (
            <ResponsiveContainer>
              <PieChart>
                <Pie data={charts.wasteByCategory} dataKey="count" nameKey="category" innerRadius={58} outerRadius={88} paddingAngle={2}>
                  {charts.wasteByCategory.map((c, i) => (
                    <Cell key={c.category} fill={CHART_COLORS[i % CHART_COLORS.length]} stroke="var(--bg-surface)" strokeWidth={2} />
                  ))}
                </Pie>
                <Tooltip contentStyle={{ background: '#0f211c', border: '1px solid rgba(150,230,200,0.2)', borderRadius: 10, fontSize: 12 }} />
              </PieChart>
            </ResponsiveContainer>
          )}
        </ChartCard>

        <ChartCard title="Waste generated by zone" subtitle="Total vs. recycled, kilograms">
          {charts.wasteByZone.length === 0 ? (
            <div className="empty-state"><span>No reports yet.</span></div>
          ) : (
            <ResponsiveContainer>
              <BarChart data={charts.wasteByZone} barGap={4}>
                <CartesianGrid stroke="var(--line-faint)" vertical={false} />
                <XAxis dataKey="zone" tick={chartTextStyle} axisLine={{ stroke: 'var(--line-faint)' }} tickLine={false} />
                <YAxis tick={chartTextStyle} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={{ background: '#0f211c', border: '1px solid rgba(150,230,200,0.2)', borderRadius: 10, fontSize: 12 }} />
                <Bar dataKey="kg" name="Total waste" fill="#4fb8e6" radius={[5, 5, 0, 0]} />
                <Bar dataKey="recycledKg" name="Recycled" fill="#49e6a6" radius={[5, 5, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          )}
        </ChartCard>
      </div>

      <div className="grid grid-2" style={{ marginBottom: 20 }}>
        <ChartCard title="Monthly waste trends" subtitle="Total kilograms reported, last 6 months">
          {charts.monthlyTrend.length === 0 ? (
            <div className="empty-state"><span>No reports yet.</span></div>
          ) : (
            <ResponsiveContainer>
              <LineChart data={charts.monthlyTrend}>
                <CartesianGrid stroke="var(--line-faint)" vertical={false} />
                <XAxis dataKey="month" tick={chartTextStyle} axisLine={{ stroke: 'var(--line-faint)' }} tickLine={false} />
                <YAxis tick={chartTextStyle} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={{ background: '#0f211c', border: '1px solid rgba(150,230,200,0.2)', borderRadius: 10, fontSize: 12 }} />
                <Line type="monotone" dataKey="kg" name="Waste (kg)" stroke="#4fb8e6" strokeWidth={2.5} dot={{ r: 3 }} />
              </LineChart>
            </ResponsiveContainer>
          )}
        </ChartCard>

        <div className="card">
          <div className="section-label">Recycling percentage</div>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: 240 }}>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 44, fontWeight: 700, color: 'var(--signal-mint)' }}>
              {charts.recyclingPercentage}%
            </div>
            <div style={{ fontSize: 12.5, color: 'var(--ink-muted)' }}>of reported items are recyclable</div>
            <div className="progress-track" style={{ width: '80%', marginTop: 16 }}>
              <div className="progress-fill mint" style={{ width: `${charts.recyclingPercentage}%` }} />
            </div>
          </div>
        </div>
      </div>

      <div className="card" style={{ marginBottom: 20 }}>
        <div className="section-label">AI Insights</div>
        {insights.length === 0 ? (
          <div className="empty-state"><span>No insights yet — insights build up as reports come in.</span></div>
        ) : (
          <div className="grid grid-2">
            {insights.map((i, idx) => (
              <div className="insight-card" key={idx}>
                <div className="insight-icon stat-icon mint" style={{ fontSize: 16 }}>{i.icon || <Sparkles size={16} />}</div>
                <div className="insight-text">{i.text}</div>
              </div>
            ))}
          </div>
        )}
      </div>

      {isAdmin && (
        <div className="card">
          <div className="section-label" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <ShieldCheck size={14} /> All reports &middot; every zone (admin only)
          </div>
          {allReports.length === 0 ? (
            <div className="empty-state"><span>No reports have been filed yet.</span></div>
          ) : (
            allReports.map((r) => (
              <div className="list-row" key={r._id}>
                <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
                  {r.imageUrl && (
                    <img src={resolveImageUrl(r.imageUrl)} alt="" style={{ width: 44, height: 44, borderRadius: 8, objectFit: 'cover' }} />
                  )}
                  <div>
                    <div style={{ fontWeight: 600, fontSize: 13.5 }}>{r.wasteType} &middot; {r.zone}</div>
                    <div style={{ fontSize: 12, color: 'var(--ink-muted)' }}>
                      Reported by {r.reportedBy?.name || 'Unknown'} &middot; {new Date(r.createdAt).toLocaleDateString()}
                    </div>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <Pill tone={priorityTone(r.priority)}>{r.priority}</Pill>
                  <Pill tone={statusTone(r.status)}>{r.status}</Pill>
                </div>
              </div>
            ))
          )}
        </div>
      )}
    </AppLayout>
  );
}
