import { useEffect, useMemo, useState } from 'react';
import { Trash2, Sparkles, AlertTriangle } from 'lucide-react';
import AppLayout from '../components/AppLayout';
import { PageHead, Pill, statusTone } from '../components/Bits';
import { api } from '../services/api';

function fillTone(fill) {
  if (fill >= 85) return 'coral';
  if (fill >= 60) return 'amber';
  if (fill >= 35) return 'azure';
  return 'mint';
}

export default function SmartBins() {
  const [zoneFilter, setZoneFilter] = useState('All');
  const [bins, setBins] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;
    api
      .getBins()
      .then((res) => { if (!cancelled) setBins(res.data || []); })
      .catch((err) => { if (!cancelled) setError(err.message || 'Failed to load bins'); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, []);

  const zones = useMemo(() => [...new Set(bins.map((b) => b.zone))].sort(), [bins]);
  const filtered = zoneFilter === 'All' ? bins : bins.filter((b) => b.zone === zoneFilter);

  return (
    <AppLayout title="Smart Bin Monitoring" subtitle="Live fill levels across every zone">
      <PageHead title="Smart Bin Monitoring" subtitle="Fill levels come from real bin records; predicted-full times are generated by the AI insight service." />

      {loading ? (
        <div className="empty-state" style={{ marginTop: 40 }}>
          <span className="spinner-ring" style={{ margin: '0 auto 10px' }} />
          <strong>Loading bins…</strong>
        </div>
      ) : error ? (
        <div className="card">
          <div className="empty-state">
            <AlertTriangle />
            <strong>Couldn't load bins</strong>
            <span>{error}</span>
          </div>
        </div>
      ) : (
        <>
          <div className="filter-row">
            {['All', ...zones].map((z) => (
              <button
                key={z}
                className={`filter-chip ${zoneFilter === z ? 'active' : ''}`}
                onClick={() => setZoneFilter(z)}
              >
                {z}
              </button>
            ))}
          </div>

          <div className="grid grid-3">
            {filtered.map((bin) => (
              <div className="card" key={bin._id}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 6 }}>
                  <div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontWeight: 600, fontSize: 15 }}>{bin.binId}</div>
                    <div style={{ fontSize: 12.5, color: 'var(--ink-muted)' }}>{bin.wasteType} &middot; {bin.zone}</div>
                  </div>
                  <Pill tone={statusTone(bin.status)}>{bin.status}</Pill>
                </div>

                <div style={{ margin: '18px 0 8px', display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                  <span style={{ fontFamily: 'var(--font-mono)', fontSize: 24, fontWeight: 700 }}>{bin.fillPercentage}%</span>
                  <span style={{ fontSize: 11.5, color: 'var(--ink-muted)' }}>fill level</span>
                </div>
                <div className="progress-track">
                  <div className={`progress-fill ${fillTone(bin.fillPercentage)}`} style={{ width: `${bin.fillPercentage}%` }} />
                </div>

                {bin.predictedFullInHours != null && (
                  <div className="insight-card" style={{ marginTop: 16 }}>
                    <div className="insight-icon stat-icon violet"><Sparkles size={14} /></div>
                    <div className="insight-text" style={{ fontSize: 12.5 }}>
                      Predicted to reach full capacity in <strong>{bin.predictedFullInHours}h</strong>.
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          {filtered.length === 0 && (
            <div className="card">
              <div className="empty-state">
                <Trash2 />
                <strong>No bins in this zone</strong>
                <span>Try selecting a different zone filter, or run the backend's seed script.</span>
              </div>
            </div>
          )}
        </>
      )}
    </AppLayout>
  );
}
