/**
 * Seeds only the campus Zone list — the one piece of reference data the app
 * genuinely needs before anyone can file a report. Everything else
 * (incidents, responder stats, analytics) is real data generated by actual
 * use, so it is deliberately NOT seeded here — seeding fake incidents would
 * just reintroduce the "hardcoded stuff" this rebuild was meant to remove.
 *
 * EDIT THE NAMES BELOW to match your actual campus blocks, then run:
 *   npm run seed
 *
 * You can also manage zones later from the admin UI (add/rename/delete)
 * without touching this file again.
 */
require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("../config/db");
const Zone = require("../models/Zone");

// --- EDIT THESE to your real Christ University Kengari campus blocks ---
const ZONE_NAMES = [
  "Psychology Block",
  "Hostel Block",
  "Centre of Excellence",
  "Main Academic Block",
  "Central Library",
  "Sports Complex",
];
// -------------------------------------------------------------------

const run = async () => {
  await connectDB();

  await Zone.deleteMany({});
  await Zone.insertMany(ZONE_NAMES.map((name) => ({ name })));

  console.log(`[Seed] Seeded ${ZONE_NAMES.length} zones: ${ZONE_NAMES.join(", ")}`);
  console.log("[Seed] No incidents, users, or responder data were seeded — that all comes from real use.");
  await mongoose.disconnect();
  process.exit(0);
};

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
