import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  PieChart,
  Pie,
  Cell,
  LineChart,
  Line,
  AreaChart,
  Area,
} from 'recharts';
import {
  Trash2,
  Recycle,
  Percent,
  Truck,
  AlertTriangle,
  MapPinned,
  TriangleAlert,
  Trash,
} from 'lucide-react';
import AppLayout from '../components/AppLayout';
import { PageHead } from '../components/Bits';
import StatCard from '../components/StatCard';
import {
  dashboardStats,
  wasteByCategory,
  wasteByZone,
  monthlyTrend,
  recyclingTrend,
  aiInsights,
} from '../data/mockData';

const iconMap = {
  'triangle-alert': TriangleAlert,
  truck: Truck,
  'trash-2': Trash2,
  recycle: Recycle,
};

const chartTextStyle = { fontSize: 11, fill: 'var(--ink-muted)' };

function ChartCard({ title, children, subtitle }) {
  return (
    <div className="card">
      <div className="section-label" style={{ marginBottom: subtitle ? 2 : 14 }}>{title}</div>
      {subtitle && <div style={{ fontSize: 11.5, color: 'var(--ink-faint)', marginBottom: 14 }}>{subtitle}</div>}
      <div style={{ width: '100%', height: 240 }}>{children}</div>
    </div>
  );
}

export default function Dashboard() {
  const s = dashboardStats;
  return (
    <AppLayout title="Smart Dashboard" subtitle="City-wide waste operations, live">
      <PageHead title="Smart Dashboard" subtitle="A live view of collection, recycling, and risk across all five zones." />

      <div className="grid grid-4" style={{ marginBottom: 20 }}>
        <StatCard icon={Trash2} tone="mint" label="Total Waste Collected" value={s.totalCollected.value} delta={s.totalCollected.delta} up={s.totalCollected.up} />
        <StatCard icon={Recycle} tone="azure" label="Total Waste Recycled" value={s.totalRecycled.value} delta={s.totalRecycled.delta} up={s.totalRecycled.up} />
        <StatCard icon={Percent} tone="violet" label="Recycling Rate" value={s.recyclingRate.value} delta={s.recyclingRate.delta} up={s.recyclingRate.up} />
        <StatCard icon={Truck} tone="amber" label="Active Pickup Requests" value={s.activePickups.value} delta={s.activePickups.delta} up={s.activePickups.up} />
        <StatCard icon={AlertTriangle} tone="coral" label="High-Risk Bins" value={s.highRiskBins.value} delta={s.highRiskBins.delta} up={s.highRiskBins.up} />
        <StatCard icon={MapPinned} tone="coral" label="Active Illegal Dumping Reports" value={s.illegalDumping.value} delta={s.illegalDumping.delta} up={s.illegalDumping.up} />
      </div>

      <div className="grid grid-2" style={{ marginBottom: 20 }}>
        <ChartCard title="Waste generated by category" subtitle="Kilograms this month">
          <ResponsiveContainer>
            <PieChart>
              <Pie data={wasteByCategory} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={2}>
                {wasteByCategory.map((c) => (
                  <Cell key={c.name} fill={c.color} stroke="var(--bg-surface)" strokeWidth={2} />
                ))}
              </Pie>
              <Tooltip contentStyle={{ background: '#0f211c', border: '1px solid rgba(150,230,200,0.2)', borderRadius: 10, fontSize: 12 }} />
            </PieChart>
          </ResponsiveContainer>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 12 }}>
            {wasteByCategory.map((c) => (
              <span key={c.name} className="pill neutral" style={{ color: c.color }}>
                <span className="pill-dot" style={{ background: c.color }} /> {c.name}
              </span>
            ))}
          </div>
        </ChartCard>

        <ChartCard title="Waste generated by zone" subtitle="Total vs. recycled, kilograms">
          <ResponsiveContainer>
            <BarChart data={wasteByZone} barGap={4}>
              <CartesianGrid stroke="var(--line-faint)" vertical={false} />
              <XAxis dataKey="zone" tick={chartTextStyle} axisLine={{ stroke: 'var(--line-faint)' }} tickLine={false} />
              <YAxis tick={chartTextStyle} axisLine={false} tickLine={false} />
              <Tooltip contentStyle={{ background: '#0f211c', border: '1px solid rgba(150,230,200,0.2)', borderRadius: 10, fontSize: 12 }} />
              <Bar dataKey="waste" name="Total waste" fill="#4fb8e6" radius={[5, 5, 0, 0]} />
              <Bar dataKey="recycled" name="Recycled" fill="#49e6a6" radius={[5, 5, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      <div className="grid grid-2" style={{ marginBottom: 20 }}>
        <ChartCard title="Monthly waste trends" subtitle="Total generated vs. recycled">
          <ResponsiveContainer>
            <AreaChart data={monthlyTrend}>
              <defs>
                <linearGradient id="wasteGrad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#4fb8e6" stopOpacity={0.35} />
                  <stop offset="100%" stopColor="#4fb8e6" stopOpacity={0} />
                </linearGradient>
                <linearGradient id="recycledGrad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#49e6a6" stopOpacity={0.4} />
                  <stop offset="100%" stopColor="#49e6a6" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid stroke="var(--line-faint)" vertical={false} />
              <XAxis dataKey="month" tick={chartTextStyle} axisLine={{ stroke: 'var(--line-faint)' }} tickLine={false} />
              <YAxis tick={chartTextStyle} axisLine={false} tickLine={false} />
              <Tooltip contentStyle={{ background: '#0f211c', border: '1px solid rgba(150,230,200,0.2)', borderRadius: 10, fontSize: 12 }} />
              <Area type="monotone" dataKey="waste" name="Waste" stroke="#4fb8e6" fill="url(#wasteGrad)" strokeWidth={2} />
              <Area type="monotone" dataKey="recycled" name="Recycled" stroke="#49e6a6" fill="url(#recycledGrad)" strokeWidth={2} />
            </AreaChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Recycling percentage" subtitle="City-wide rate by month">
          <ResponsiveContainer>
            <LineChart data={recyclingTrend}>
              <CartesianGrid stroke="var(--line-faint)" vertical={false} />
              <XAxis dataKey="month" tick={chartTextStyle} axisLine={{ stroke: 'var(--line-faint)' }} tickLine={false} />
              <YAxis tick={chartTextStyle} axisLine={false} tickLine={false} unit="%" />
              <Tooltip contentStyle={{ background: '#0f211c', border: '1px solid rgba(150,230,200,0.2)', borderRadius: 10, fontSize: 12 }} />
              <Line type="monotone" dataKey="rate" name="Recycling rate" stroke="#a68cf0" strokeWidth={2.5} dot={{ r: 3, fill: '#a68cf0' }} />
            </LineChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      <div className="card">
        <div className="section-label">AI Insights</div>
        <div className="grid grid-2">
          {aiInsights.map((i) => {
            const Icon = iconMap[i.icon] || Trash;
            return (
              <div className="insight-card" key={i.id}>
                <div className={`insight-icon stat-icon ${i.tone}`}><Icon size={16} /></div>
                <div className="insight-text">{i.text}</div>
              </div>
            );
          })}
        </div>
      </div>
    </AppLayout>
  );
}
