import { useEffect, useRef, useState } from 'react';
import { Camera, ImagePlus, Loader2, Sparkles, CheckCircle2, RotateCcw, Truck } from 'lucide-react';
import AppLayout from '../components/AppLayout';
import { api, resolveImageUrl } from '../services/api';

const SEVERITY_TONE = { Low: 'mint', Medium: 'azure', High: 'amber', Critical: 'coral' };

export default function ReportIncident() {
  const [zones, setZones] = useState([]);
  const [zonesLoading, setZonesLoading] = useState(true);
  const [zone, setZone] = useState('');
  const [note, setNote] = useState('');
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [dragActive, setDragActive] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const inputRef = useRef(null);

  useEffect(() => {
    api
      .getZones()
      .then((data) => {
        setZones(data);
        if (data.length > 0) setZone(data[0].name);
      })
      .catch(() => setError('Could not load campus zones. Is the backend running?'))
      .finally(() => setZonesLoading(false));
  }, []);

  const pickFile = (f) => {
    if (!f) return;
    setFile(f);
    setPreview(URL.createObjectURL(f));
    setError('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!file) return setError('Add a photo of the area first.');
    if (!zone) return setError('Select a zone.');

    setSubmitting(true);
    setError('');
    try {
      const incident = await api.reportIncident({ zone, citizenNote: note, image: file });
      setResult(incident);
    } catch (err) {
      setError(err.message || 'Something went wrong analyzing the photo.');
    } finally {
      setSubmitting(false);
    }
  };

  const reset = () => {
    setResult(null);
    setFile(null);
    setPreview(null);
    setNote('');
  };

  if (result) {
    const tone = SEVERITY_TONE[result.severity] || 'azure';
    return (
      <AppLayout title="Report an Area" subtitle="AI triage complete">
        <div className="grid" style={{ gridTemplateColumns: '1fr 1.2fr', gap: 24, alignItems: 'start' }}>
          <div className="card">
            <img src={resolveImageUrl(result.imageUrl)} alt="Reported area" className="ticket-photo" style={{ height: 260 }} />
            <div className="pill mint" style={{ marginBottom: 10 }}>
              <CheckCircle2 size={13} /> Report submitted
            </div>
            <p style={{ fontSize: 13 }}>
              Zone: <strong style={{ color: 'var(--ink-primary)' }}>{result.zone}</strong>
            </p>
          </div>

          <div className={`ticket sev-${result.severity.toLowerCase()}`}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
              <div className="insight-icon violet" style={{ background: 'var(--signal-violet-bg)', color: 'var(--signal-violet)' }}>
                <Sparkles size={16} />
              </div>
              <div>
                <div style={{ fontWeight: 600, fontSize: 14.5 }}>AI Report</div>
                <div style={{ fontSize: 11.5, color: 'var(--ink-faint)' }}>
                  {result.aiSource === 'ai' ? 'Generated by Gemini' : 'Mock response — no AI key configured'}
                  {typeof result.aiConfidence === 'number' && ` · ${result.aiConfidence}% confidence`}
                </div>
              </div>
            </div>

            <p style={{ fontSize: 14, color: 'var(--ink-primary)', marginBottom: 18, lineHeight: 1.6 }}>{result.aiReport}</p>

            <div className="grid grid-2" style={{ marginBottom: 18 }}>
              <div>
                <div className="field-hint" style={{ marginBottom: 6 }}>Severity</div>
                <span className={`pill ${tone}`}>{result.severity}</span>
              </div>
              <div>
                <div className="field-hint" style={{ marginBottom: 6 }}>Dispatch</div>
                <span className={`pill ${result.dispatchRequired ? 'amber' : 'neutral'}`}>
                  <Truck size={12} /> {result.dispatchRequired ? 'Team dispatch recommended' : 'Routine round is fine'}
                </span>
              </div>
            </div>

            <div style={{ marginBottom: 18 }}>
              <div className="field-hint" style={{ marginBottom: 8 }}>Waste types detected</div>
              <div className="radio-row">
                {result.wasteTypes.map((wt) => (
                  <span key={wt} className="radio-chip selected">{wt}</span>
                ))}
              </div>
            </div>

            {result.recommendedResources?.length > 0 && (
              <div style={{ marginBottom: 22 }}>
                <div className="field-hint" style={{ marginBottom: 8 }}>Recommended for the response team</div>
                <ul style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {result.recommendedResources.map((r, i) => (
                    <li key={i} style={{ fontSize: 13, color: 'var(--ink-secondary)' }}>· {r}</li>
                  ))}
                </ul>
              </div>
            )}

            <button className="btn btn-primary" onClick={reset}>
              <RotateCcw size={15} /> Report another area
            </button>
          </div>
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout title="Report an Area" subtitle="Photograph a messy or full area — AI does the rest">
      <form className="card" style={{ maxWidth: 640 }} onSubmit={handleSubmit}>
        <div
          className={`dropzone ${dragActive ? 'drag' : ''}`}
          onClick={() => inputRef.current?.click()}
          onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
          onDragLeave={() => setDragActive(false)}
          onDrop={(e) => { e.preventDefault(); setDragActive(false); pickFile(e.dataTransfer.files?.[0]); }}
        >
          {preview ? (
            <img src={preview} alt="Preview" style={{ maxHeight: 220, borderRadius: 10, margin: '0 auto' }} />
          ) : (
            <>
              <ImagePlus />
              <div>Tap to take a photo or upload one</div>
              <div className="field-hint" style={{ marginTop: 4 }}>JPG, PNG or WEBP</div>
            </>
          )}
        </div>
        <input
          ref={inputRef}
          type="file"
          accept="image/*"
          capture="environment"
          hidden
          onChange={(e) => pickFile(e.target.files?.[0])}
        />

        <div className="field" style={{ marginTop: 20 }}>
          <label>Zone</label>
          {zonesLoading ? (
            <div className="skeleton" style={{ height: 42, borderRadius: 8 }} />
          ) : zones.length === 0 ? (
            <p className="field-hint">No zones have been set up yet — ask an admin to add campus zones first.</p>
          ) : (
            <select className="select" value={zone} onChange={(e) => setZone(e.target.value)}>
              {zones.map((z) => (
                <option key={z._id} value={z.name}>{z.name}</option>
              ))}
            </select>
          )}
        </div>

        <div className="field">
          <label>Add context (optional)</label>
          <textarea
            className="textarea"
            placeholder="Anything the response team should know..."
            value={note}
            onChange={(e) => setNote(e.target.value)}
          />
        </div>

        {error && <p style={{ color: 'var(--signal-coral)', fontSize: 12.5, marginBottom: 14 }}>{error}</p>}

        <button className="btn btn-primary btn-block btn-lg" type="submit" disabled={submitting || zonesLoading}>
          {submitting ? (
            <>
              <Loader2 size={16} className="spin" style={{ animation: 'spin 0.8s linear infinite' }} /> AI is analyzing the photo...
            </>
          ) : (
            <>
              <Camera size={16} /> Send to AI
            </>
          )}
        </button>
      </form>
    </AppLayout>
  );
}
